name: Whiskers Check

on:
  push:
    paths: ['jellyfin.tera', 'themes', '.github/workflows/whiskers.yml']
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: catppuccin/setup-whiskers@v2.0.0
        with:
          whiskers-version: '2.5.1'
      - run: whiskers jellyfin.tera --check
